week_16/Bonus Python/big_als_record_store/big_als_record_store/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('inventory/', include("inventory.urls")),
    path('admin/', admin.site.urls)
]

week_16/Bonus Python/big_als_record_store/inventory/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.index, name="index")
]

week_16/Bonus Python/big_als_record_store/inventory/models.py
from django.db import models

class Artist(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Album(models.Model):
    title = models.CharField(max_length=255)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE)
    stock_level = models.IntegerField()

    def __str__(self):
        return self.title

week_16/Bonus Python/big_als_record_store/inventory/views.py
from django.shortcuts import render
from inventory.models import *

def index(request):
    all_artists = Artist.objects.all()
    context = {
        "all_artists": all_artists
    }
    return render(request, "index.html", context)

week_16/Bonus Python/big_als_record_store/inventory/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Big Als</title>
</head>

<body>
  <h1>All Artists</h1> {% for artist in all_artists %}
  <p>{{ artist.name }}</p>
  <h2>Album List</h2> {% for album in artist.album_set.all %}
  <p>{{album.title}} - {{album.stock_level}}</p>
  {% endfor %} {% endfor %}
</body>

</html>